import { Constants } from '@auxo-dev/dkg';
export const INSTANCE_LIMITS = {
    PROJECT_TREE_SIZE: 2 ** 5,
    PROJECT_MEMBER_TREE_SIZE: 2 ** 3,
    ZKAPP_ADDRESS_TREE_SIZE: 2 ** 4,
    CAMPAIGN_TREE_SIZE: 2 ** 5,
    PARTICIPATION_INDEX_TREE_SIZE: 2 ** 5 * 2 ** 5,
    PARTICIPATION_SLOT_TREE_SIZE: Constants.REQUEST_MAX_SIZE,
    COMMITMENT_HASH_TREE_SIZE: 2 ** 8,
};

export const MINIMAL_MINA_UNIT = 100000000n;

export enum ZkAppEnum {
    COMMITTEE,
    DKG,
    ROUND1,
    ROUND2,
    RESPONSE,
    REQUEST,
    PROJECT,
    CAMPAIGN,
    PARTICIPATION,
    FUNDING,
    TREASURY,
}
